// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG0LZG9mW1CFK_GcTA3n20pR_lB6hTPZ4',
    appId: '1:326366707466:web:3bce2056e04a4cf99704f3',
    messagingSenderId: '326366707466',
    projectId: 'my-personal-project-d4740',
    authDomain: 'my-personal-project-d4740.firebaseapp.com',
    storageBucket: 'my-personal-project-d4740.appspot.com',
    measurementId: 'G-0JLM4VDDJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifIiIEPDlmo0VYrSQ2SsRgqj6V1hOPxU',
    appId: '1:326366707466:android:f949c8f2e0cbf8c39704f3',
    messagingSenderId: '326366707466',
    projectId: 'my-personal-project-d4740',
    storageBucket: 'my-personal-project-d4740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTJtEg1G49imsMZWB5-GXsRRWCmSba_M',
    appId: '1:326366707466:ios:cded0029c1ffbb3e9704f3',
    messagingSenderId: '326366707466',
    projectId: 'my-personal-project-d4740',
    storageBucket: 'my-personal-project-d4740.appspot.com',
    iosClientId: '326366707466-vds1pt99rqv4cemrd7v24gfj7sm3t1vp.apps.googleusercontent.com',
    iosBundleId: 'com.malekkashoqa.personalProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvTJtEg1G49imsMZWB5-GXsRRWCmSba_M',
    appId: '1:326366707466:ios:cded0029c1ffbb3e9704f3',
    messagingSenderId: '326366707466',
    projectId: 'my-personal-project-d4740',
    storageBucket: 'my-personal-project-d4740.appspot.com',
    iosClientId: '326366707466-vds1pt99rqv4cemrd7v24gfj7sm3t1vp.apps.googleusercontent.com',
    iosBundleId: 'com.malekkashoqa.personalProject1',
  );
}
